### ISSUE TITLE
problème d'accent

### ISSUE THREAD

**Issue by vadlefou** [cxii-dev/script.tvshowtime#29]
C'est de nouveau moi, le problème persiste lors de la synchro kodi vers tvshow lorsque la série comporte un accent (éèçà..)

Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 26: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-master\program.py", line 202, in <module>
                                                start()
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-master\program.py", line 56, in start
                                                first_step()
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-master\program.py", line 101, in first_step
                                                scan(which_way, tvshowsid[whattvshow])
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-master\program.py", line 167, in scan
                                                checkin = MarkAsWatched(__token__, filename, __facebook__, __twitter__)
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-master\resources\lib\tvshowtime.py", line 96, in __init__
                                                'publish_on_twitter' : self.twitter
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1332, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 26: ordinal not in range(128)
                                            -->End of Python script error report<--

Par contre y aurait-il une solution pour synchro les grosses bdd (750 séries), car cela s'arrete au bout d'un moment (du a la limite des 60secondes je pense).
A part faire les séries une par une, mais cela n'est pas très pratique.

Merci d'avance

**Comment by cxii-dev** [comment]
Bonjour,

En plein développement pour la 1.1.0, j'ai résolu le problème des accents en utilisant l'id unique de l'épisode.
Je suis occupé de revoir certaines parties du code et d'ajouter des fonctionalités avec l'ajout dans l'api

Pour les grandes bdd, il y a peut-être une nouveauté dans l'api mais je dois encore m'y plonger ...

Voici un lien pour la version de dev: https://github.com/cxii-dev/script.tvshowtime-dev
https://github.com/cxii-dev/script.tvshowtime-dev/archive/master.zip

**Comment by vadlefou** [comment]
Merci, je test de suite.

Si besoin d'un testeur de grosses bdd, je suis là.

**Comment by cxii-dev** [comment]
Ok super

**Comment by vadlefou** [comment]
Vvec la version de dev plus de problème d'accent.
La synchro se fait bien.
Merci

**Comment by cxii-dev** [comment]
La 1.1.1 est sortie en dev
J'ai changé la façon de synchroniser les db

**Comment by vadlefou** [comment]
ok, je vais regarder ça.
je fais un retour si besoin

**Comment by vadlefou** [comment]
j'ai une erreur au lancement de la synchro lors de l'initialisation.

Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('episodes',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 247, in <module>
                                                start()
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 61, in start
                                                first_step()
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 84, in first_step
                                                scan(which_way)
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 128, in scan
                                                tvshowList = getTvshowList()
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 173, in getTvshowList
                                                episodes = episodes['result']['episodes']
                                            KeyError: ('episodes',)
                                            -->End of Python script error report<--

**Comment by cxii-dev** [comment]
Voilà, j'ai ajouté une sécurité quand il n'y a pas d'épisodes dans une série

**Comment by vadlefou** [comment]
Pourtant j'ai bien des épisodes dans chaques séries.
Sinon effectivement la synchro n'a rien à voir, cela prend quelques secondes pour tout parcourir, et lorsque je regarde les logs, tout semble là.
Par contre, cela ne met pas à jour sur le site.
Des séries qui n'étaient pas ajoutées manuellement sur le site et ne le sont pas lors d'une synchro.
Et même si j'ajoute une de mes séries manuellement sur le site, lors de la synchro, cela ne marque pas les épisodes vus.

voila le log si besoin :
https://www.dropbox.com/s/a5b41nt4ptbq9eu/kodi.log?dl=0

**Comment by cxii-dev** [comment]
J'ai rajouté une ligne log dans le script car il s'arrète à un endroit ou il ne devrait pas ...

**Comment by vadlefou** [comment]
effectivement plus d'arret dans le log, mais le comportement reste le même.
Pas de mise à jour sur le site.
voir nouveau log
https://www.dropbox.com/s/2uc729519zf3soy/kodi2.log?dl=0

**Comment by cxii-dev** [comment]
et comme ceci ?

**Comment by vadlefou** [comment]
Parfait ça marche.
Par contre, ça me marque tout en déjà vu alors que je les ai pas encore regardé.

**Comment by vadlefou** [comment]
D'ailleurs c'est assez étrange, pour les ajouts de séries qui n'etaient pas encore ajouter sur tvshow, elles sont bien ajoutées, mais en déjà vu.
Et certaines séries déjà ajoutée, ne sont pas mis à jour ou certaines se retrouvent en déjà vu aussi.

**Comment by cxii-dev** [comment]
Je ne t'oublies pas ...
J'ai trouvé le pb, la requête DELETE ne fonctionnait pas.
J'ai fini le code, j'attend confirmation de la part de TVShow Time pour te mettre à dispo une version qui va corriger le pb d'hier. et concidérablement réduire le temps de synchro :)

**Comment by vadlefou** [comment]
je ne m'en fais pas, en quelques jours tu as fait un sacré travail déjà.
déjà que le temps a été super réduit, j'ai hate de voir ta prochaine release.

**Comment by cxii-dev** [comment]
Voilà, je l'ai testé avec ma db et mis dans le dev pour toi. Dis moi quoi

**Comment by vadlefou** [comment]
alors l'initialisation commence.
il affiche une de mes série, puis au bout de quelques secondes : terminée.
mais pas de mise à jour.

log : https://www.dropbox.com/s/uu1rwg02utup3is/kodi3.log?dl=0

**Comment by cxii-dev** [comment]
Tu aurais le nom d'une série que tu n'as pas commencé ?

**Comment by vadlefou** [comment]
bien sur
je viens de rajouter "Sense8".

**Comment by cxii-dev** [comment]
Voilà, j'ai changé quelque peut

**Comment by vadlefou** [comment]
ça me fait toujours la même chose.
Il bloque sur la première série, puis terminé.
Tu veux que je t'envoi ma base?

**Comment by cxii-dev** [comment]
Le log?

**Comment by vadlefou** [comment]
non ma base sql directement.

le log est la : https://www.dropbox.com/s/9do4aihhwi99mfm/kodi4.log?dl=0

**Comment by cxii-dev** [comment]
Je veux bien la db des séries ... ça sera plus facile avec une grande liste .. :D

**Comment by vadlefou** [comment]
J'utilise une base mysql, j'espère que ça ne te pose pas de problème.
ma base : https://www.dropbox.com/s/ypx780zy8woo30b/kodi_20150804.zip?dl=0

**Comment by cxii-dev** [comment]
Je vais juste éviter de l'appeler commema db :)

**Comment by vadlefou** [comment]
ça roule.
désolé de te monopoliser comme ça.
Et merci encore

**Comment by cxii-dev** [comment]
Pas de soucis, j'aime quand ça fonctionne :)

**Comment by vadlefou** [comment]
c'est en bonne voie en tout cas =)

**Comment by cxii-dev** [comment]
Voici une dernière version pour cette nuit.
Je ne sais pas si elle va bien synchroniser le tout (car je crois qu'il y a encore une limitation chez TVST que je ne connais pas ... je demanderai demain) mais tu devrais être capable de lire le log et me dire si c'est correct ... :P

**Comment by vadlefou** [comment]
Alors le comportement de synchro me semble pas mal.
Les logs plus compréhensible.
J'en ai vérifier plusieurs (Dofus, Bones, Sense8), les derniers épisodes sont les bons.
Mais toujours rien sur le site :(

log : https://www.dropbox.com/s/n1i7owk14rborgn/kodi5.log?dl=0

**Comment by cxii-dev** [comment]
Ok :)

J'ai demandé à TVST quel est la limite par requête car dans ton cas, il y a 353 séries à modifier comme vues
Par contre Magnum et Melrose Place sont a marqué comme jamais commencé ...

**Comment by vadlefou** [comment]
je pense que ça doit faire ça effectivement, 353 commencées et 259 terminées.
Par contre, truc étrange, mon xbmc me marque 723 séries, alors que dans ton log, je n'en compte que 720.
oui magnum et melrose place ne sont pas commencée.

**Comment by cxii-dev** [comment]
Voilà, j'ai ajouté un découpage par 50, j'espère que ça va passer comme ça

**Comment by vadlefou** [comment]
malheureusement ça ne passe pas non plus.
Les noms défilent bien, mais tout n'est pas updater :/
il y a des séries qui ont bien été rajoutées, mais pas toutes.

**Comment by cxii-dev** [comment]
Je peux avoir le log ? On avance :)

**Comment by vadlefou** [comment]
Jai édité le post en mettant le lien


Envoyé depuis mon Galaxy."New is always better"<div>
</div><div>
</div><div>-------- Message d'origine --------</div><div>De : cxii-dev <notifications@github.com> </div><div>Date : 05/08/2015  12:51  (GMT+01:00) </div><div>À : "cxii-dev/script.tvshowtime" <script.tvshowtime@noreply.github.com> </div><div>Cc : vadlefou <vladlefou@hotmail.fr> </div><div>Objet : Re: [script.tvshowtime] problème d'accent (#29) </div><div>
</div>
Je peux avoir le log ? On avance :)

Sent from my iPhone

> On 5 août 2015, at 12:12, vadlefou <notifications@github.com> wrote:
>
> malheureusement ça ne passe pas non plus.
> Les noms défilent bien, mais tout n'est pas updater :/
> il y a des séries qui ont bien été rajoutées, mais pas toutes.
>
> —
> Reply to this email directly or view it on GitHub.
>


---

**Comment by cxii-dev** [comment]
Voilà, normalement maintenant ça devrait aller :D

**Comment by vadlefou** [comment]
bon allez c'est pas grand chose cette fois.. =)

16:16:14 T:6340   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'test' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 357, in <module>
                                                start()
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 65, in start
                                                first_step()
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 88, in first_step
                                                scan(which_way)
                                              File "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py", line 154, in scan
                                                total = int(len(test))+int(len(showsNotSeen))
                                            NameError: global name 'test' is not defined
                                            -->End of Python script error report<--

**Comment by cxii-dev** [comment]
HA oui c'est mon test :D

On Wed, Aug 5, 2015 at 4:17 PM, vadlefou <notifications@github.com> wrote:

> bon allez c'est pas grand chose cette fois.. =)
>
> 16:16:14 T:6340 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python
> callback/script returned the following error<--
> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
> Error Type:
> Error Contents: global name 'test' is not defined
> Traceback (most recent call last):
> File
> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
> line 357, in
> start()
> File
> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
> line 65, in start
> first_step()
> File
> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
> line 88, in first_step
> scan(which_way)
> File
> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
> line 154, in scan
> total = int(len(test))+int(len(showsNotSeen))
> NameError: global name 'test' is not defined
> -->End of Python script error report<--
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cxii-dev/script.tvshowtime/issues/29#issuecomment-128012205>
> .
>



-- 



*Alexandre S. Koperweb solutions**Save paper: think before you print.*

**Comment by cxii-dev** [comment]
Voilà mis à jour

On Wed, Aug 5, 2015 at 4:26 PM, Alexandre Koper <alexkoper@gmail.com> wrote:

> HA oui c'est mon test :D
>
> On Wed, Aug 5, 2015 at 4:17 PM, vadlefou <notifications@github.com> wrote:
>
>> bon allez c'est pas grand chose cette fois.. =)
>>
>> 16:16:14 T:6340 ERROR: EXCEPTION Thrown (PythonToCppException) :
>> -->Python callback/script returned the following error<--
>> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>> Error Type:
>> Error Contents: global name 'test' is not defined
>> Traceback (most recent call last):
>> File
>> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
>> line 357, in
>> start()
>> File
>> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
>> line 65, in start
>> first_step()
>> File
>> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
>> line 88, in first_step
>> scan(which_way)
>> File
>> "C:\Users\Vlad\AppData\Roaming\Kodi\addons\script.tvshowtime-dev-master\program.py",
>> line 154, in scan
>> total = int(len(test))+int(len(showsNotSeen))
>> NameError: global name 'test' is not defined
>> -->End of Python script error report<--
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cxii-dev/script.tvshowtime/issues/29#issuecomment-128012205>
>> .
>>
>
>
>
> --
>
>
>
> *Alexandre S. Koperweb solutions**Save paper: think before you print.*
>



-- 



*Alexandre S. Koperweb solutions**Save paper: think before you print.*

**Comment by vadlefou** [comment]
plus d'erreur, mais ne met toujours pas à jour.
la ligne ou tu liste toutes les séries n'est pas trop grande pour l'api?
comme tu as coupé les updates, peut être celle la aussi, non?

et ptite question, pourquoi à la fin tu supprime la progression de 2 séries?

**Comment by cxii-dev** [comment]
Arf pas normal ça
c'est juste une liste donc pas de soucis pour la taille ...
tu aurais la fin du log ? avec les saveprogress et les is_set ?

Je ne supprime pas vraiement, je les renseignes comme non commencées

**Comment by vadlefou** [comment]
lorsque je regarde la liste, exemple Sense8, l'id (268156) n'apparait que dans la list et non dans les progessions et non commencées en dessous.
voila le log : https://www.dropbox.com/s/cts67x8295e2n0u/kodi7.log?dl=0

**Comment by cxii-dev** [comment]
Tu as les 12 épisodes?

**Comment by vadlefou** [comment]
oui, pourquoi?
tu n'ajoute que les séries si elles sont complètes?

**Comment by cxii-dev** [comment]
Non dutout
1 je liste les séries
2 je liste les épisodes de la série
3 je regarde le dernier épisode vu
S'il y en a un je le dit a tvst
Sinon
4 je regarde le premier épisode non vu
Si celui-ci est s01e01 alors je le dit a tvst
Sinon je ne fait rien

**Comment by vadlefou** [comment]
okay.
du coup s'il manque des épisodes dans une saison, ils sont marqués comme vu aussi.

**Comment by cxii-dev** [comment]
Si tu en passe alors oui ...
Sinon n'imagine même pas le temps de synchro ... 50.000 épisodes 3 jours

**Comment by vadlefou** [comment]
ca se tente, non :p

**Comment by cxii-dev** [comment]
Bon allez, restons raisonables ...
Allez encore une version pour sense8

**Comment by vadlefou** [comment]
ouarf, jsuis désolé, mais ca ne veut toujours pas :(
log : https://www.dropbox.com/s/v4jyy19nfmlo1w3/kodi8.log?dl=0

**Comment by cxii-dev** [comment]
Je viens de remettre les épisodes dans le log car je ne comprend pas pourquoi il dit que le dernier non vu est le s01e12

**Comment by vadlefou** [comment]
bon le log est plus conséquent, mais le résultat est le même
https://www.dropbox.com/s/k5x0gopoe3mozyn/kodi9.log?dl=0

**Comment by cxii-dev** [comment]
J'ai encore rendu le log plus lourd ...
Je ne comprend pas pk il ne prend pas le premier ... (alors que chez moi oui ..)

**Comment by vadlefou** [comment]
c'est clair qu'il fait son poids..
les lignes d'update ne sont pas encore trop longue? ou le temps entre chaque update.

**Comment by cxii-dev** [comment]
Non c'est au niveau du traitement qu'il y a un problème ...
J'ose espérer qu'un i7 2.67GHz peut traiter une ligne de 1ko :D
Tu aurais le kodi10.log ?

**Comment by vadlefou** [comment]
ca fait toujours la même chose
le voila : https://www.dropbox.com/s/pyqiq80levuvv9v/kodi10.log?dl=0

**Comment by raspdealer** [comment]
Je suis vos échanges depuis le début car cet add-on me tient également à cœur.
Est ce qu'il ne serait pas plus simple que vadlefou fasse un batch qui scan son dossier de séries et recréer à côté une image mais que avec des fichiers de 1ko ?
Du coup il serait plus facile de reproduire les problèmes...

**Comment by cxii-dev** [comment]
Ici je ne comprend pas pourquoi le code:

firstEpisode = None
firstSeasonNr = 2
firstEpisodeNr = 2
if (episode['season'] <= firstSeasonNr):
   firstSeasonNr = episode['season']
   firstEpisodeNr = episode['episode']
   firstEpisode = episode
elif (episode['season'] == firstSeasonNr and episode['episode'] < firstEpisodeNr):                        
   firstEpisodeNr = episode['episode']
   firstEpisode = episode

retourne s01e12 alors que dans ma version il retourne s01e01

**Comment by cxii-dev** [comment]
Enfn si je viens de comprendre ...

**Comment by cxii-dev** [comment]
Voilà vadlefou, je viens de mettre une nouvelle version

**Comment by vadlefou** [comment]
raspdealer : cela risque de prendre encore plus de temps que je scanne moi même mes répertoires (plusieurs disques dur), alors que j'ai une base mysql avec toutes les informations à l’intérieur.
D'autant que cxii arrive a récupérer les infos directement.

je test de suite cxii

**Comment by cxii-dev** [comment]
avec ton fichier mysql ça fonctionne chez moi
Sense8 = premier_non_vu = s01e01

**Comment by vadlefou** [comment]
et bien chez moi ça ne passe toujours pas.
pourtant j'ai la même chose que toi dans les logs..
https://www.dropbox.com/s/5ne0laof9zug2yt/kodi11.log?dl=0

est ce que tvshowtime ne bloque pas l'ip au bout de x tentative

**Comment by cxii-dev** [comment]
que veux-tu dire que ça ne fonctionne pas ?
Si je regarde les 2 dernières lignes du log, il dit que tu n'as jamais vu sense8 et qu'il l'a bien pris en compte sur TVST ...

**Comment by vadlefou** [comment]
bah effectivement dans le log c'est bon.
Mais ensuite sur le site, je ne vois pas les séries ajoutées.
le compteur reste à 554 et lorsque je recherche Sense8, et bien il me propose de l'ajouté.

**Comment by cxii-dev** [comment]
Ca c'est normal ... :D
Si tu ne l'as jamais regardé, le code actuel ne l'ajoute pas ... (ouf)
Il faut que je rajoute cette fonction ...

**Comment by vadlefou** [comment]
haaaaa...
ça aurait pu continué longtemps comme ça..
mais comme tu marquais le dernier épisode vu, et que pour les séries non commencées, tu avais le premier épisode, je pensais que ça les rajoutaient en même temps.

**Comment by vadlefou** [comment]
du coup, je te confirme que ça marche.
je viens de vérifier plusieurs séries, c'est bien à jour =)
c'est parfait

**Comment by cxii-dev** [comment]
J'attend le retour de TVST pour le multiple follow et on sera bon alors :)

**Comment by vadlefou** [comment]
je pense aussi.
j'attends la suite pour ton debug ;)

**Comment by nonobio** [comment]
Bonjour,
Je viens d'installer l'addon kodi de tvshowtime version 1.0.18 et j'ai un problème de synchronisation avec apparemment les séries avec accents (exemple : nus et cullotés).
Le problème devrait il être résolu ? Est ce un autre problème ?
Merci

**Comment by vadlefou** [comment]
J'ai suivi les conseil de cxii, et depuis j'utilise la version de dev : https://github.com/cxii-dev/script.tvshowtime-dev
je n'ai aucun problème de synchro avec les accents.

**Comment by nonobio** [comment]
Salut,
De quels conseils parles-tu ? Le conseil est il juste d'utiliser la version de dev ?
J'ai suivi ton lien et téléchargé le fichier avec le bouton "download zip". J'ai installé l'extension via kodi avec "installer à partir d'un fichier zip". J'ai maintenant Tvshow Time "dev" en version 1.1.1 en plus de la version installée depuis l'addon manager de Kodi (1.0;18). Pour éviter tout conflit j'ai désactivé la 1.0.18. J'ai lancé la 1.1.1 depuis programmes : je me suis reconnecté et ai tenté une synchro de Kodi vers TVShowtime : contrairement à l'ancienne version je n'ai pas pu faire une selection des séries à synchroniser et j'ai encore un message "echec du script" :(.

**Comment by cxii-dev** [comment]
Salut Vad, la version de dev fonctionne correctement chez toi ?

**Comment by vadlefou** [comment]
Depuis la dernière version que tu avais faites, tout fonctionne.
Je l'ai même installé sur un autre poste et la synchro se fait bien.

**Comment by nonobio** [comment]
Salut,
Je viens de réessayer une synchro de Kodi vers TVShowtime : echec du script. Je peux vous envoyer un log si vous voulez : j'active le debugging de kodi et vous envoi le log ?
@+

**Comment by cxii-dev** [comment]
Bonjour,

Oui tu peux m'envoyer le log.

Bien à toi

**Comment by nonobio** [comment]
Salut,
Tu es français ?
Voici le debug log pour lequel j'ai fait les actions suivantes : démarré Kodi, Programmes, TVshowtime : synchonisation "Kodi vers TVShowtime" : error script. J'ai refait la même opération une seconde fois puis quitté kodi.

Le log vis xbmclogs :
[](http://www.xbmclogs.com/phl5ope0n)

Le log via pastebin :
[](http://pastebin.com/6DWLBne6)

Quel est ta préférence pour les logs ? Est ce que le collage dans le message avec balise "code" suffit ?

Merci
à+

**Comment by eraser-head** [comment]
I've similar problem with dev version addon in kodi 16.0RC3, now I can login successfully, but when I try sync my shows whatched list two secons after show me a message that the sync it's ok, but really not.

**Comment by cxii-dev** [comment]
@nonobio Bonjour, j'ai modifié le log de la version de dev. si tu pouvais tester et me retourner le log si erreur ?
@eraser-head Hello, could you send me a debug log ?

**Comment by eraser-head** [comment]
here you have

http://xbmclogs.com/pmyg9yok7

my kody log uploader doesn't work fine too, when is going to upload the log fail...

**Comment by nonobio** [comment]
> @nonobio Bonjour, j'ai modifié le log de la version de dev. si tu pouvais tester et me retourner le log si erreur ?

Salut :)

Pour installer la nouvelle version, il faut que je télécharges le zip à l'aide du bouton download zip" de cette page ? : [https://github.com/cxii-dev/script.tvshowtime](url)

J'ai un peu de mal à m'y retrouver sur github..

Je n'aurais pas de mise à jour auto via kodi si je n'installes pas la version dispo vai le repo kodi n'est ce pas ?

**Comment by eraser-head** [comment]
Any suggestion?

**Comment by cxii-dev** [comment]
The v1.1.0 (beta) solve the problem. I will pull it on github by the end of the day and by the end of the week on kodi's repo
