### ISSUE TITLE
TVT unable to sync.

### ISSUE THREAD

**Issue by REDdimension** [cxii-dev/script.tvshowtime#30]
My TVT/Kodi installation is unable to sync with TVT. Every command the plugins tries to send meets with an error and refers me to the logs.

**Comment by cxii-dev** [comment]
Could you send me some logs ?

Cheers

**Comment by kate66** [comment]
Here is the log whenever I attempt to sync from Kodi to TVT, I hope that it helps.

20:32:33 T:5244   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\script.tvshowtime\program.py", line 202, in <module>
                                                start()
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\script.tvshowtime\program.py", line 56, in start
                                                first_step()
                                              File "C:\Users\htpc\AppData\Roaming\Kodi\addons\script.tvshowtime\program.py", line 82, in first_step
                                                tvshows.append(result['result']['tvshows'][i]['label'])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by kate66** [comment]
Note, I am using 16.0 Beta 2, so I'm in for this already. :)

**Comment by cxii-dev** [comment]
Hello, I tried with the 16.0 RC3 and no errors, have you tried with it too ? Have you the same problem ?

**Comment by movieaddct** [comment]
how did u get it to sync with kodi???

**Comment by smeapng** [comment]
Hello, I have the same problem with the final version of kodi 16.
LOG:
20:53:56 2082.867920 T:1733030896   ERROR: Previous line repeats 1 times.
20:53:56 2082.868164 T:1733030896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.tvshowtime/program.py", line 202, in <module>
                                                start()
                                              File "/home/osmc/.kodi/addons/script.tvshowtime/program.py", line 56, in start
                                                first_step()
                                              File "/home/osmc/.kodi/addons/script.tvshowtime/program.py", line 82, in first_step
                                                tvshows.append(result['result']['tvshows'][i]['label'])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--


Thank you for your help.

Cordially.

**Comment by dragonslore** [comment]
Hello,

I created a new topic but I just noticed this one was about the same issue I met lately.

`01:01:23 T:1538750768   DEBUG: int CVideoDatabase::RunQuery(const string&) took 65 ms for 131 items query: SELECT * FROM tvshow_view
01:01:23 T:1538750768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvshowtime/program.py", line 202, in <module>
                                                start()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvshowtime/program.py", line 56, in start
                                                first_step()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvshowtime/program.py", line 82, in first_step
                                                tvshows.append(result['result']['tvshows'][i]['label'])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--`


If it can help to solve the issue :)

Thanks & Regards

**Comment by dragonslore** [comment]
I just followed this topic and installed DEV version...everything work properly now.

https://github.com/cxii-dev/script.tvshowtime/issues/29

**Comment by cxii-dev** [comment]
Ok, I will pull the dev to the master by the end of the week ..
Thank's guys

**Comment by badenf** [comment]
Hi

I cannot for the life of me get TVST to scrobble the shows I watch with Kodi. I have Trakt and TVShow Time installed. Trakt scrobbles and notifies but nothing from TVST.

I am using KODI 16 and using Exodus to watch the shows.

When I load KODI i receive the welcome username but this will be the last notification I receive from TVST.

Any suggestions?

Thanks,

**Comment by cxii-dev** [comment]
Hi, Hare you using the 1.1.2 ?

**Comment by badenf** [comment]
No I am using version 1.0.18

I am pulling it from the Kodi repository. How do I get the latest?

Sorry I am new to the Kodi / repository world.

Thanks for your help and quick response.

**Comment by badenf** [comment]
Never mind. I managed to figure it out.

Now to get it installed on my fire stick. Any idea when the latest will be available through the KODI repository?

Thanks

**Comment by badenf** [comment]
Managed to download the latest version from your github and install it on the fire
stick.

This article explains everything very easily for anyone else having difficulty.

https://seo-michael.co.uk/how-to-push-zip-files-to-fire-stick-with-adbfire/
