### ISSUE TITLE
Addon crash since I moved to Kodi 16.0

### ISSUE THREAD

**Issue by dragonslore** [cxii-dev/script.tvshowtime#43]
Hi,

I'm a french Guy, I use your addon since a while now and never got any issue with it.
Since I moved to Kodi 16.0 I get this error in my logs as soon as I want to sync Kodi with TVShowTime.
I have the last 1.0.18 version of the addon.

Do you have any idea ?

```
12:29:31 T:1565661488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvshowtime/program.py", line 202, in <module>
                                                start()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvshowtime/program.py", line 56, in start
                                                first_step()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvshowtime/program.py", line 82, in first_step
                                                tvshows.append(result['result']['tvshows'][i]['label'])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```

Thanks for your help :)

Manu

**Comment by dragonslore** [comment]
I close my topic as an existing one already exists for the same issue: https://github.com/cxii-dev/script.tvshowtime/issues/30
