### ISSUE TITLE
Fatal error during login

### ISSUE THREAD

**Issue by RomainSarry** [cxii-dev/script.tvshowtime#56]
Hi,
The add-on stopped working a few days ago. I tried to uninstall and reinstall it but when I try to login I get the following error :

> ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.TypeError'>
>                                             Error Contents: 'NoneType' object has no attribute '__getitem__'
>                                             Traceback (most recent call last):
>                                               File "C:\Users\Romain\AppData\Roaming\Kodi\addons\script.tvshowtime\program.py", line 367, in <module>
>                                                 start()
>                                               File "C:\Users\Romain\AppData\Roaming\Kodi\addons\script.tvshowtime\program.py", line 55, in start
>                                                 Authorization(_login.verification_url, _login.user_code, _login.device_code)
>                                               File "C:\Users\Romain\AppData\Roaming\Kodi\addons\script.tvshowtime\program.py", line 75, in Authorization
>                                                 _authorize = Authorize(device_code)
>                                               File "C:\Users\Romain\AppData\Roaming\Kodi\addons\script.tvshowtime\resources\lib\tvshowtime.py", line 632, in __init__
>                                                 self.message = data['message']
>                                             TypeError: 'NoneType' object has no attribute '__getitem__'
>                                             -->End of Python script error report<--`

**Comment by felipemm** [comment]
Hi,

To fix that, just comment out the line 632 on Kodi\addons\script.tvshowtime\resources\lib\tvshowtime.py:

        if (data is None) or (data['result'] == "KO"):
           self.is_authorized = False
           #self.message = data['message']
        else:
           self.is_authorized = True
           self.access_token = data['access_token']
