### ISSUE TITLE
Synchronization between KODI en TVShow keeps failing

### ISSUE THREAD

**Issue by lwolfs** [cxii-dev/script.tvshowtime#57]
Hello,
Started with TVShow, and would like to sync with my KODI on raspberry. ( KODI is version 17.6 on LibreElec 8.2.1)
When I start syncing from KODI>TVShow I see the following error: "check the log for more information."
Syncing aborts. I did some debugging to find out where the error comes from, and this is what I found:

14:09:09.309 T:1858077600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.tvshowtime/program.py", line 367, in <module>
                                                start()
                                              File "/storage/.kodi/addons/script.tvshowtime/program.py", line 66, in start
                                                first_step()
                                              File "/storage/.kodi/addons/script.tvshowtime/program.py", line 89, in first_step
                                                scan(which_way)
                                              File "/storage/.kodi/addons/script.tvshowtime/program.py", line 149, in scan
                                                'show_id': int(tvshowList['show_id']),
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
14:09:09.418 T:1858077600    INFO: Python script stopped
 
Code from the Python script:

            if tvshowList['seen'] == 1:
                showsSeen.append({
                    'show_id': int(tvshowList['show_id']),
                    'season': tvshowList['season'],
                    'episode': tvshowList['episode']
                })
            elif tvshowList['seen'] == 0 and tvshowList['season'] == 1 and tvshowList['episode'] == 1:
                showsNotSeen.append({
                    'show_id': int(tvshowList['show_id'])
                })

Can you help in solving this issue ?

Thx !

**Comment by Jorg8** [comment]
It is the first time I use this addon (Kodi on nexus player android tv) and I have seen that this error happens because the content of `tvshowList ['show_id']` corresponds to the IMDB id and start with "tt" so it can not be converted to integer.
It also happens to me but at the moment I have not tried to change it and see what happens.

**Comment by ilansas** [comment]
Same trouble for me

**Comment by zachside** [comment]
Hello, same trouble for me. Sync from Kodi to TV Show is not working (kodi on openelec on raspberryPi). I'll check the log if it can help.

**Comment by felipesalomao** [comment]
I have exactly same problem, i am running kodi 17.6 on raspbian, raspberry pi 3. it cant sync.. same error in log.. Somebody know how fix it? 

See  log

```
05:06:41.321 T:1638507264   DEBUG: ### [TVShow Time] - list=[{'season': 5, 'show_id': 257655, 'episode': 6, 'title': u'Arrow'}, {'season': 2, 'show_id': 295647, 'episode': 4, 'title': u'Blindspot'}, {'season': 5, 'show_id': 81189, 'episode': 16, 'title': u'Breaking Bad'}, {'season': 2, 'show_id': 284210, 'episode': 13, 'title': u'Colony'}, {'season': 1, 'show_id': 292174, 'episode': 13, 'title': u'Dark Matter'}, {'season': 8, 'show_id': 79349, 'episode': 12, 'title': u'Dexter'}, {'season': 3, 'show_id': 290853, 'episode': 14, 'title': u'Fear the Walking Dead'}, {'season': 6, 'show_id': 121361, 'episode': 10, 'title': u'Game of Thrones'}, {'season': 3, 'show_id': 274431, 'episode': 7, 'title': u'Gotham'}, {'season': 5, 'show_id': 247897, 'episode': 12, 'title': u'Homeland'}, {'season': 2, 'show_id': 292124, 'episode': 8, 'title': u'Humans'}, {'season': 1, 'show_id': 295760, 'episode': 16, 'title': u'Legends of Tomorrow'}, {'season': 2, 'show_id': 281662, 'episode': 13, 'title': u"Marvel's Daredevil"}, {'season': 2, 'show_id': 289590, 'episode': 1, 'title': u'Mr. Robot'}, {'season': 1, 'show_id': 282670, 'episode': 10, 'title': u'Narcos'}, {'season': 5, 'show_id': 248742, 'episode': 13, 'title': u'Person of Interest'}, {'season': 4, 'show_id': 75340, 'episode': 22, 'title': u'Prison Break'}, {'season': 1, 'show_id': 176941, 'episode': 2, 'title': u'Sherlock'}, {'season': 1, 'show_id': 305288, 'episode': 8, 'title': u'Stranger Things'}, {'season': 5, 'show_id': 268592, 'episode': 2, 'title': u'The 100'}, {'season': 3, 'show_id': 279121, 'episode': 3, 'title': u'The Flash (2014)'}, {'season': 4, 'show_id': 269533, 'episode': 10, 'title': u'The Last Ship'}, {'season': 1, 'show_id': 337480, 'episode': 8, 'title': u'The Mechanism'}, {'season': 2, 'show_id': 276564, 'episode': 13, 'title': u'The Strain'}, {'season': 8, 'show_id': 153021, 'episode': 16, 'title': u'The Walking Dead'}, {'season': 1, 'show_id': 311713, 'episode': 3, 'title': u'Timeless (2016)'}, {'season': 2, 'show_id': 296762, 'episode': 3, 'title': u'Westworld'}, {'season': 2, 'show_id': 280494, 'episode': 15, 'title': u'Z Nation'}]
05:06:41.350 T:1638507264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 367, in <module>
                                                start()
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 66, in start
                                                first_step()
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 89, in first_step
                                                scan(which_way)
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 223, in scan
                                                if int(tvshowList[i]['show_id']) == int(tvshowTime['show_id']):
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
05:06:41.509 T:1638507264    INFO: Python script stopped
```
