### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by the-lazy-fox** [cxii-dev/script.tvshowtime#67]
I'm wondering if our pull requests will be merge?
I have made a fork, feel free to use it.

https://github.com/alxlaxv/script.tvtime

**Comment by felipesalomao** [comment]
Hi, i have problem to sync it in kodi using  raspbian (raspberry pi 3).. it gives this error:

```
05:06:41.321 T:1638507264   DEBUG: ### [TVShow Time] - list=[{'season': 5, 'show_id': 257655, 'episode': 6, 'title': u'Arrow'}, {'season': 2, 'show_id': 295647, 'episode': 4, 'title': u'Blindspot'}, {'season': 5, 'show_id': 81189, 'episode': 16, 'title': u'Breaking Bad'}, {'season': 2, 'show_id': 284210, 'episode': 13, 'title': u'Colony'}, {'season': 1, 'show_id': 292174, 'episode': 13, 'title': u'Dark Matter'}, {'season': 8, 'show_id': 79349, 'episode': 12, 'title': u'Dexter'}, {'season': 3, 'show_id': 290853, 'episode': 14, 'title': u'Fear the Walking Dead'}, {'season': 6, 'show_id': 121361, 'episode': 10, 'title': u'Game of Thrones'}, {'season': 3, 'show_id': 274431, 'episode': 7, 'title': u'Gotham'}, {'season': 5, 'show_id': 247897, 'episode': 12, 'title': u'Homeland'}, {'season': 2, 'show_id': 292124, 'episode': 8, 'title': u'Humans'}, {'season': 1, 'show_id': 295760, 'episode': 16, 'title': u'Legends of Tomorrow'}, {'season': 2, 'show_id': 281662, 'episode': 13, 'title': u"Marvel's Daredevil"}, {'season': 2, 'show_id': 289590, 'episode': 1, 'title': u'Mr. Robot'}, {'season': 1, 'show_id': 282670, 'episode': 10, 'title': u'Narcos'}, {'season': 5, 'show_id': 248742, 'episode': 13, 'title': u'Person of Interest'}, {'season': 4, 'show_id': 75340, 'episode': 22, 'title': u'Prison Break'}, {'season': 1, 'show_id': 176941, 'episode': 2, 'title': u'Sherlock'}, {'season': 1, 'show_id': 305288, 'episode': 8, 'title': u'Stranger Things'}, {'season': 5, 'show_id': 268592, 'episode': 2, 'title': u'The 100'}, {'season': 3, 'show_id': 279121, 'episode': 3, 'title': u'The Flash (2014)'}, {'season': 4, 'show_id': 269533, 'episode': 10, 'title': u'The Last Ship'}, {'season': 1, 'show_id': 337480, 'episode': 8, 'title': u'The Mechanism'}, {'season': 2, 'show_id': 276564, 'episode': 13, 'title': u'The Strain'}, {'season': 8, 'show_id': 153021, 'episode': 16, 'title': u'The Walking Dead'}, {'season': 1, 'show_id': 311713, 'episode': 3, 'title': u'Timeless (2016)'}, {'season': 2, 'show_id': 296762, 'episode': 3, 'title': u'Westworld'}, {'season': 2, 'show_id': 280494, 'episode': 15, 'title': u'Z Nation'}]
05:06:41.350 T:1638507264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 367, in <module>
                                                start()
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 66, in start
                                                first_step()
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 89, in first_step
                                                scan(which_way)
                                              File "/root/.kodi/addons/script.tvshowtime/program.py", line 223, in scan
                                                if int(tvshowList[i]['show_id']) == int(tvshowTime['show_id']):
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
05:06:41.509 T:1638507264    INFO: Python script stopped
```

Do you know if your version fixed? its possible to install your version of tvtime here? I tried download, link failed, also url seems does not exist.. I think that this repository is no longer active..

**Comment by the-lazy-fox** [comment]
Download the last release and try.
https://github.com/alxlaxv/script.tvtime/releases

**Comment by felipesalomao** [comment]
Installed.. Had exactly same error.. I run kodi 17.6 on raspberry pi (raspbian), do you not have this problem? When i sync tv show time > kodi.. It show this error.. 

```
15:58:55.586 T:1911025664   ERROR: Window Translator: Can't find window games
16:04:53.270 T:1639969536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/script.tvtime/program.py", line 367, in <module>
                                                start()
                                              File "/root/.kodi/addons/script.tvtime/program.py", line 66, in start
                                                first_step()
                                              File "/root/.kodi/addons/script.tvtime/program.py", line 89, in first_step
                                                scan(which_way)
                                              File "/root/.kodi/addons/script.tvtime/program.py", line 223, in scan
                                                if int(tvshowList[i]['show_id']) == int(tvshowTime['show_id']):
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
```
